In [76]:
import pandas as pd
import numpy as np
df = pd.read_csv("./datasets/playstore_limpio.csv")

In [77]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9632,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000.0,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
9633,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100.0,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
9634,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,1000.0,Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
9635,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000.0,Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
9636,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000.0,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

Reto 1: La Trampa de las Unidades de Medida
El equipo de infraestructura quiere saber si las aplicaciones más pesadas tienen menos descargas. Para averiguarlo, necesitan que la columna Size sea completamente numérica. Sin embargo, si revisan la columna, encontrarán valores como "19M" (Megabytes), "201k" (Kilobytes) y un texto molesto que dice "Varies with device".

Tu misión algorítmica:
1.- Escribe una función pura en Python que reciba un string. Si el string termina en 'M', quítale la 'M' y conviértelo a flotante (dejándolo como Megabytes). Si termina en 'k', quítale la 'k', conviértelo a flotante y divídelo entre 1024 (para pasarlo también a Megabytes). Si dice "Varies with device", devuélvelo como un valor nulo de Numpy (np.nan).

In [78]:
def parse_sizes(size):
    if size[-1] == 'M':
        return float(size[:-1])
    elif size[-1] == 'k':
        return float(size[:-1] )/ 1024
    return np.nan

2.- Aplica esta función a toda la columna utilizando el método .apply().

In [79]:
df['Size'] = df['Size'].apply(parse_sizes)

Pregunta a responder: Una vez convertida la columna a valores numéricos (Megabytes), ejecuta el método .mean(). ¿Cuál es el peso promedio en Megabytes de las apps en la Play Store?

In [80]:
df['Size'].mean()

np.float64(20.41973193945847)

Reto 2: El Tipo de Dato Cronológico
Ningún análisis de software está completo sin analizar el tiempo. La columna Last Updated tiene fechas escritas como texto: "January 7, 2018". Para un modelo matemático o una serie de tiempo, eso es texto inservible.

1.- Tu misión algorítmica:
Investiga y utiliza la función pd.to_datetime() de Pandas para sobrescribir la columna Last Updated, convirtiéndola del tipo string (Object) al tipo nativo datetime64.

In [81]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'], format='%B %d, %Y', errors='coerce')

2.- Ahora que es un objeto de tiempo, Pandas te permite extraer componentes específicos. Crea una nueva columna llamada Year_Updated extrayendo únicamente el año (df['Last Updated'].dt.year).

In [82]:
df['Year_Updated'] = df['Last Updated'].dt.year

Pregunta a responder: Utilizando la sumarización categórica (value_counts()) sobre tu nueva columna Year_Updated, ¿en qué año se actualizó la mayor cantidad de aplicaciones en nuestro dataset?

In [83]:
df['Year_Updated'].value_counts()

Year_Updated
2018.0    6271
2017.0    1785
2016.0     779
2015.0     448
2014.0     203
2013.0     108
2012.0      26
2011.0      15
2010.0       1
Name: count, dtype: int64

En el año 2018 hubo la mayor actualizacion de aplicaciones

Reto 3: La Decisión Arquitectónica
Al resolver el Reto 1, introdujiste intencionalmente valores NaN en las aplicaciones cuyo tamaño decía "Varies with device".

Tu misión algorítmica:

1.- Evalúa cuántos registros quedaron vacíos. Como ingenieros, decidan y apliquen la mejor técnica: ¿es matemáticamente más sano borrar esas filas con un .dropna() porque el peso de la app es crítico, o prefieren rellenar ese hueco imputando la mediana global del peso de las apps?

In [84]:
df['Size'].isna().sum() / df['Size'].count()  * 100

np.float64(14.603401117849923)

In [85]:
df[df['Size'].isna()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Year_Updated
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,NaN,5000000.0,Free,0.0,Everyone,Art & Design,2018-07-14,Varies with device,2.3.3 and up,2018.0
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,NaN,10000000.0,Free,0.0,Everyone,Art & Design,2018-07-30,Varies with device,Varies with device,2018.0
52,Used Cars and Trucks for Sale,AUTO_AND_VEHICLES,4.6,17057,NaN,1000000.0,Free,0.0,Everyone,Auto & Vehicles,2018-07-30,Varies with device,Varies with device,2018.0
67,Ulysse Speedometer,AUTO_AND_VEHICLES,4.3,40211,NaN,5000000.0,Free,0.0,Everyone,Auto & Vehicles,2018-07-30,Varies with device,Varies with device,2018.0
68,REPUVE,AUTO_AND_VEHICLES,3.9,356,NaN,100000.0,Free,0.0,Everyone,Auto & Vehicles,2018-05-25,Varies with device,Varies with device,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9514,My Earthquake Alerts - US & Worldwide Earthquakes,WEATHER,4.4,3471,NaN,100000.0,Free,0.0,Everyone,Weather,2018-07-24,Varies with device,Varies with device,2018.0
9524,Posta App,MAPS_AND_NAVIGATION,3.6,8,NaN,1000.0,Free,0.0,Everyone,Maps & Navigation,2017-09-27,Varies with device,4.4 and up,2017.0
9562,Chat For Strangers - Video Chat,SOCIAL,3.4,622,NaN,100000.0,Free,0.0,Mature 17+,Social,2018-05-23,Varies with device,Varies with device,2018.0
9622,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,NaN,5000000.0,Free,0.0,Mature 17+,Social,2018-03-23,Varies with device,Varies with device,2018.0
9635,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000.0,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,2015.0

Consido debido a que estas aplicaciones no son ruido en la base de datos y los valores de NaN es más del 10%, matemáticamente considero que es más sano rellenarlo con la mediana global

In [86]:
df['Size'].sum()

np.float64(171709.52587890625)

In [87]:
df['Size'] = df['Size'].fillna(df['Size'].median())

In [75]:
df['Size'].sum()

np.float64(186445.52587890625)

Pregunta a responder: Redacten una breve justificación técnica de 3 líneas explicando qué método eligieron y por qué lo consideran superior para no dañar al modelo de predicción.

Considero que es una buena manera de limpiar los datos, ya que al reemplazar los valores nulos con la mediana, se evita que los valores extremos afecten el promedio, esto nos ayuda a mantener una forma de mostrar un tamaño más probable de las aplicaciónes sin tener skewness de outliers